"""Post-processing of LLM responses.

Cleans up common artefacts — question echoing and partial "no
information" disclaimers — and appends formatted source citations when
source documents are provided.
"""

import re
from typing import Any

from rag_chatbot.question_parser import remove_question_repetition

_NO_INFO_EXACT = "I don't have enough information to answer this question."
_NO_INFO_MARKER = "don't have enough information"
_NO_INFO_SPLIT_PATTERN = re.compile(
    r"(I don't have enough information to answer [^.]*\.)",
    re.IGNORECASE,
)


def format_response_with_citations(
    response: str,
    question: str,
    source_documents: list[Any] | None = None,
) -> str:
    """Clean an LLM response and append source citations.

    Processing steps (applied in order):

    1. If the response is the exact "no information" boilerplate, it is
       returned unchanged.
    2. If the response *contains* a "no information" segment mixed with
       other text, the response is split on that segment; non-disclaimer
       parts are cleaned for question repetition and then reassembled.
    3. Any leading sentence that restates the user's question is removed.
    4. Source documents are deduplicated by ``(source, page)`` and
       appended as numbered citations.

    Args:
        response: The raw text generated by the LLM.
        question: The user's original question (used for repetition
            detection).
        source_documents: Optional list of LangChain ``Document`` objects
            whose ``.metadata`` dicts supply ``"source"`` and ``"page"``
            fields.

    Returns:
        The cleaned response string, potentially with an appended
        ``Sources:`` section.
    """
    # Step 1 — verbatim "no information" reply
    if response.strip() == _NO_INFO_EXACT:
        return response

    # Step 2 — partial "no information" mixed with substantive content
    if _NO_INFO_MARKER in response.lower():
        parts = _NO_INFO_SPLIT_PATTERN.split(response)
        if len(parts) > 1:
            cleaned_parts: list[str] = []
            for part in parts:
                stripped = part.strip()
                if not stripped:
                    continue
                if _NO_INFO_MARKER in stripped.lower():
                    cleaned_parts.append(stripped)
                else:
                    cleaned = remove_question_repetition(stripped, question)
                    if cleaned.strip():
                        cleaned_parts.append(cleaned.strip())
            response = " ".join(cleaned_parts)

    # Step 3 — drop leading question echo
    response = remove_question_repetition(response, question)

    # Step 4 — deduplicate and format source citations
    if source_documents:
        unique_sources: dict[str, dict[str, Any]] = {}
        for doc in source_documents:
            source_name = doc.metadata.get("source", "Unknown Document")
            page_number = doc.metadata.get("page", "N/A")
            dedup_key = f"{source_name}-{page_number}"
            if dedup_key not in unique_sources:
                unique_sources[dedup_key] = {
                    "source": source_name,
                    "page": page_number,
                }

        if unique_sources:
            citation_text = "\n\n\nSources:\n"
            for index, source_info in enumerate(unique_sources.values(), start=1):
                citation_text += (
                    f"{index}. {source_info['source']}, "
                    f"page {source_info['page']}\n"
                )
            response += citation_text

    return response
